export enum ErrorStatus {
  FILE_NOT_FOUND_OR_INVALID = 'FILE_NOT_FOUND_OR_INVALID',
  FILE_IS_EMPTY = 'FILE_IS_EMPTY',
  MAXIMUM_WEIGHT_CAPACITY_EXCEEDED = 'MAXIMUM_WEIGHT_CAPACITY_EXCEEDED',
  MAXIMUM_ITEM_WEIGHT_EXCEEDED = 'MAXIMUM_ITEM_WEIGHT_EXCEEDED',
  MAXIMUM_ITEM_COST_EXCEEDED = 'MAXIMUM_ITEM_COST_EXCEEDED',
  MAXIMUM_ITEM_NUMBER_EXCEEDED = 'MAXIMUM_ITEM_NUMBER_EXCEEDED',
}
